from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database.connection import get_db
from app.middleware.auth import CurrentUser
from app.schemas.skills import (
    SkillGapResponse,
    RoadmapGenerateRequest,
    RoadmapGenerateResponse,
    RoadmapStep,
)
from app.services.skill_analyzer import get_skill_gap
from app.services.roadmap_generator import create_roadmap, get_user_roadmaps

router = APIRouter(tags=["Skills & Roadmap"])

SUPPORTED_ROLES = [
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Engineer",
    "Data Scientist",
    "AI/ML Engineer",
    "DevOps Engineer",
    "Mobile Developer",
]


# ── GET /skills/roles ─────────────────────────────────────────────────────────

@router.get(
    "/skills/roles",
    summary="List supported target roles",
)
def list_roles():
    return {"roles": SUPPORTED_ROLES}


# ── GET /skills/{role} ────────────────────────────────────────────────────────

@router.get(
    "/skills/{role}",
    response_model=SkillGapResponse,
    summary="Get skill gap analysis for a role (uses latest resume skills if available)",
)
async def skill_gap(
    role: str,
    current_user: CurrentUser,
    resume_id: int | None = None,
    db: Session = Depends(get_db),
):
    result = await get_skill_gap(role, resume_id, db)
    return SkillGapResponse(
        role=result["role"],
        current_skills=result.get("current_skills", []),
        missing_skills=result.get("missing_skills", []),
        roadmap=[RoadmapStep(**s) for s in result.get("roadmap", [])],
    )


# ── POST /roadmap/generate ────────────────────────────────────────────────────

@router.post(
    "/roadmap/generate",
    response_model=RoadmapGenerateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate and save an AI career roadmap",
)
async def generate_roadmap(
    payload: RoadmapGenerateRequest,
    current_user: CurrentUser,
    db: Session = Depends(get_db),
):
    result = await create_roadmap(
        user_id=current_user.id,
        target_role=payload.target_role,
        current_skills=payload.current_skills,
        db=db,
    )
    return RoadmapGenerateResponse(
        target_role=result["target_role"],
        steps=[RoadmapStep(**s) for s in result.get("steps", [])],
    )


# ── GET /roadmap/history ──────────────────────────────────────────────────────

@router.get(
    "/roadmap/history",
    summary="Get all roadmaps generated by the current user",
)
def roadmap_history(
    current_user: CurrentUser,
    db: Session = Depends(get_db),
):
    return {"roadmaps": get_user_roadmaps(current_user.id, db)}
